[Refactor] Replacing PyPDF2 deprecated usage
Submitty/InstructorTools pull request #28
Opened 2022-05-25 15:51 UTC by akshatbatra

As a part of updating PyPDF2 version to 1.28.2, some changes have been made to conform to the latest API.

2022-05-30 00:30 UTC, Eceptonsu approved these changes

2022-06-24 16:52 UTC, MasterOdin requested changes

2022-06-24 16:52 UTC, MasterOdin commented on QR_TestMaker/make_all.py
> +    overlay = PyPDF2.PdfFileReader(overlay_file, strict=False)
```suggestion
    overlay = PyPDF2.PdfReader(overlay_file, strict=False)
```

This should be applied to the other references to this class.

2022-06-25 17:28 UTC, MasterOdin approved these changes

2022-06-25 17:29 UTC, merged